"""empty message

Revision ID: 19083eeb0601
Revises: c7f53834622f
Create Date: 2021-05-04 10:32:35.751381

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '19083eeb0601'
down_revision = 'c7f53834622f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name'))
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=10), nullable=True))

    op.drop_table('category')
    # ### end Alembic commands ###
