"""empty message

Revision ID: 33c83e165d86
Revises: ba2a9cb22ec5
Create Date: 2021-03-10 17:17:28.195769

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '33c83e165d86'
down_revision = 'ba2a9cb22ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    op.add_column('question', sa.Column('ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'ip')
    op.drop_column('answer', 'ip')
    # ### end Alembic commands ###
