"""empty message

Revision ID: 51267fecac8f
Revises: 19083eeb0601
Create Date: 2021-05-04 10:36:58.108800

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '51267fecac8f'
down_revision = '19083eeb0601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_question_category_name_category'), 'category', ['category_name'], ['name'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_category_name_category'), type_='foreignkey')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
