"""empty message

Revision ID: 5e9b621b70a3
Revises: 60ac3e14a958
Create Date: 2021-05-05 13:37:18.308734

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5e9b621b70a3'
down_revision = '60ac3e14a958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.VARCHAR(length=20), nullable=True))

    op.create_table('category',
    sa.Column('name', sa.NUMERIC(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###
