"""empty message

Revision ID: 60ac3e14a958
Revises: 772317a4f08a
Create Date: 2021-05-05 13:35:46.998684

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '60ac3e14a958'
down_revision = '772317a4f08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=20), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_category_name_category', type_='foreignkey')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key('fk_question_category_name_category', 'category', ['category_name'], ['name'], ondelete='CASCADE')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
