"""empty message

Revision ID: 6e30accbfc49
Revises: 33c83e165d86
Create Date: 2021-03-26 11:10:41.344784

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6e30accbfc49'
down_revision = '33c83e165d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('answer', 'ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'answer', ['ip'])
    op.alter_column('question', 'ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'question', ['ip'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='unique')
    op.alter_column('question', 'ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'answer', type_='unique')
    op.alter_column('answer', 'ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('user')
    # ### end Alembic commands ###
